name: Deploy Admin Panel

on:
  push:
    branches:
      - main  # deploy happens on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies & Build
      - name: Install & Build
        run: |
          cd smsreactadminpannel
          npm install
          npm run build

      # 4. Deploy to S3
      - name: Deploy to S3
        uses: aws-actions/s3-sync@v1
        with:
          source-dir: smsreactadminpannel/build  # adjust if build folder is different
          dest-bucket: sms-frontend-all1
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
