name: Deploy Partner App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-partner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Build (Partner App)
        working-directory: smsreactpartnerpannel-sharmila
        run: |
          npm install
          npm run build

      - name: Deploy to S3 (Partner App)
        run: |
          aws s3 sync smsreactpartnerpannel-sharmila/dist/ s3://sms-frontend-app/partner --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
