name: Deploy Partner Panel

on:
  push:
    branches:
      - main  # Deploys automatically on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build   # For Vite use 'build', for CRA change folder to ./build

      # 5️⃣ Upload build folder to S3
      - name: Upload to S3
        run: aws s3 sync ./dist s3://sms-frontend-all1/partner --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1

      # 6️⃣ Debug CloudFront ID (optional, ensures secret is set)
      - name: Debug CloudFront ID
        run: echo "CloudFront ID is '${{ secrets.CLOUDFRONT_DIST_ID }}'"

      # 7️⃣ Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/partner/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
