name: Deploy React App to S3

on:
  push:
    branches:
      - main   # whenever you push to main, it deploys

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          source-dir: build/   # or dist/ if your build folder is dist
          dest-bucket: sms-frontend-all1
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
